server:
  port: 8895
spring:
  datasource:
    url: jdbc:sqlite:auxiliary.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql_logging: true
